name: vibeforge
description: "Material3 Ui Music Player."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  just_audio: ^0.9.36
  lottie: ^3.0.0
  metadata_god: ^0.5.2+1
  permission_handler: ^11.2.1
  searchbar_animation: ^0.0.4
  shared_preferences: ^2.2.2
  action_slider: ^0.7.0
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  file_picker: ^6.1.1
  ncs_io: ^0.0.4
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2  
  google_fonts: ^4.0.4
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/
    - assets/images/
    - assets/music/
    - assets/covers/
    


  fonts:
    - family: ProtestRiot-Regular
      fonts:
        - asset: assets/fonts/ProtestRiot-Regular.ttf
    - family: ProtestRevolution-Regular
      fonts:
        - asset: assets/fonts/ProtestRevolution-Regular.ttf
    
